version: '3.7'

services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend
    ports:
      - "5432:5432"
  polymedic_app:
    build: .
    command: python main.py
    volumes:
      - .:/usr/src/polymedic_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge